### ISSUE TITLE
Files driver and log rotation

### ISSUE THREAD

**Issue by peacand** [cea-sec/openwec#171]
It seems like the Files driver does not support well file rotation. 

I mean: 
- I configure a file output to /var/log/data/wec.log
- I configure logrotate to rotate this log file one time a day 

When the log file is rotated (the file /var/log/data/wec.log is moved to /var/log/data/wec.log.1), the original file does not exist anymore, and it looks like openwec does not detect the file does not exist and does not recreate it. At least, it does not do it as soon as there are new logs to write. It might do it after some kind of timeouts/garbage collection interval but in the meantime, some logs have been missed and not written to the output file.

**Comment by vruello** [comment]
Hi! Similar to many services, you need to send a SIGHUP signal to openwec to notify it that the files have been rotated. On receipt of a SIGHUP, openwec closes all open files and then re-opens them in append mode when needed.

With logrotate, you can use a postrotate script that looks like this:
```
    postrotate
            /bin/kill -HUP `cat /var/run/openwecd.pid 2>/dev/null` 2>/dev/null || true
    endscript
```

By the way, when logrotate or another tool moves a file used by the Files driver of openwec, openwec continues to write to the moved file as long as its file descriptor remains open (i.e. until a SIGHUP signal is received OR the file descriptor is "garbage collected"). That's why you didn't see a new file being created.

**Comment by peacand** [comment]
Perfect ! Thank you so much for the clarification @vruello
